# Generated by Django 5.1.3 on 2024-11-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Player',
            new_name='Jogador',
        ),
        migrations.RenameField(
            model_name='jogador',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='created_at',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='player',
            new_name='jogador',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='points',
            new_name='pontos',
        ),
    ]
