# Generated by Django 5.0.4 on 2024-11-25 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_rename_player_jogador_rename_name_jogador_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jogador',
            options={'verbose_name_plural': 'Jogadores'},
        ),
    ]
